### ISSUE TITLE
为什么不用migratie的方式来实现数据库可移植性

### ISSUE THREAD

**Issue by zzhgithub** [rang9527/laravel51#1]
为什么不用migratie的方式来实现数据库可移植性?
可以在项目 根目录下运行 php artisan migrate
就可以自动生成数据库 非常的优雅.
但是前提是你要在之前运行migration指令

**Comment by rang9527** [comment]
你说的很对，当时写的时候还不太喜欢migration

**Comment by zzhgithub** [comment]
好的那你准备改吗？？如果你不更新版本的话我来改为migratie方式来实现可移植。然后提交合并请求吧。不过我比较懒 可能过一段时间~ : )

**Comment by rang9527** [comment]
后面可能会用5.2重写

**Comment by zzhgithub** [comment]
好的那我就不折腾了 期待你早日写好
